name: Read Version from File
on:
  workflow_dispatch:


jobs:
  read_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version from file
        id: read_version
        run: echo "::set-env name=VERSION::$(cut -d '|' -f 2 /assets/VERSION)"

      - name: Use version in subsequent steps
        run: echo "Version is ${{ env.VERSION }}"
